import os
import json
from os import listdir
from os.path import isfile, join
# --------------- configuration start here --------------------------------------------------------------------------
# Path to checkpoint file or a directory containing checkpoint files. Passing
# a directory will only work if there is also a file named 'checkpoint' which
# lists the available checkpoints in the directory. It will not work if you
# point to a directory with just a copy of a model checkpoint: in that case,
# you will need to pass the checkpoint path explicitly.

CHECKPOINT_PATH = "../../pretrained_models/labels/classification/classify_image_graph_def.pb"

# Vocabulary file generated by the preprocessing script.
VOCAB_DIR = "../../pretrained_models/labels/classification/"
# -------------------configuration end here-----------------------------------------------------------------------

# JPEG image file to label
import tkinter as tk
from tkinter import filedialog
from tkFileDialog import askopenfilename

root = tk.Tk()
root.withdraw()
x = askopenfilename(initialdir='../test/')

IMAGE_FILE = x

CODE_PATH = "library"
# Run inference to generate captions.
os.system(
    "python " + CODE_PATH + "/classify_image_demo.py --checkpoint_path=" + CHECKPOINT_PATH + " --vocab_dir=" + VOCAB_DIR + " --input_file=" + IMAGE_FILE)

print("Classified Label Generating Completed!")
press = raw_input("Press any key to quit \n")
